site_name: Leyline – Tenets & Bindings
site_description: Centralized development standards as tenets and bindings
site_author: Phaedrus
site_url: https://phrazzld.github.io/leyline/

# Repository
repo_name: phrazzld/leyline
repo_url: https://github.com/phrazzld/leyline

# Navigation
nav:
  - Home: index.md
  - Tenets:
    - Overview: tenets/00-index.md
    - Simplicity: tenets/simplicity.md
    - Modularity: tenets/modularity.md
    - Testability: tenets/testability.md
    - Explicit Over Implicit: tenets/explicit-over-implicit.md
    - Maintainability: tenets/maintainability.md
    - Document Decisions: tenets/document-decisions.md
    - Automation: tenets/automation.md
    - No Secret Suppression: tenets/no-secret-suppression.md
  - Bindings:
    - Overview: bindings/00-index.md
    - Core Bindings:
      - API Design: bindings/core/api-design.md
      - Automate Changelog: bindings/core/automate-changelog.md
      - Code Size: bindings/core/code-size.md
      - Component Architecture: bindings/core/component-architecture.md
      - Context Propagation: bindings/core/context-propagation.md
      - Dependency Inversion: bindings/core/dependency-inversion.md
      - Dependency Management: bindings/core/dependency-management.md
      - External Configuration: bindings/core/external-configuration.md
      - Hex Domain Purity: bindings/core/hex-domain-purity.md
      - Immutable By Default: bindings/core/immutable-by-default.md
      - No Internal Mocking: bindings/core/no-internal-mocking.md
      - No Lint Suppression: bindings/core/no-lint-suppression.md
      - Pure Functions: bindings/core/pure-functions.md
      - Require Conventional Commits: bindings/core/require-conventional-commits.md
      - Semantic Versioning: bindings/core/semantic-versioning.md
      - Use Structured Logging: bindings/core/use-structured-logging.md
    - TypeScript:
      - No Any: bindings/categories/typescript/no-any.md
      - Module Organization: bindings/categories/typescript/module-organization.md
      - Async Patterns: bindings/categories/typescript/async-patterns.md
    - Go:
      - Error Wrapping: bindings/categories/go/error-wrapping.md
      - Interface Design: bindings/categories/go/interface-design.md
      - Package Design: bindings/categories/go/package-design.md
      - Concurrency Patterns: bindings/categories/go/concurrency-patterns.md
    - Rust:
      - Error Handling: bindings/categories/rust/error-handling.md
      - Ownership Patterns: bindings/categories/rust/ownership-patterns.md
    - Frontend:
      - State Management: bindings/categories/frontend/state-management.md
      - Web Accessibility: bindings/categories/frontend/web-accessibility.md
  - Integration:
    - Migration Guide: migration-guide.md
    - Implementation Guide: implementation-guide.md
  - Documentation:
    - Formatting Standards: TENET_FORMATTING.md
    - Storybook Standards: STORYBOOK_TENETS_SLASH_BINDINGS.md
    - Style Guide: STYLE_GUIDE_NATURAL_LANGUAGE.md
    - LLM Integration: LLM_INTEGRATION.md
  - Announcements:
    - YAML-only Format (May 2025): announcements/yaml-only-format-2025-05.md
  - Contributing: CONTRIBUTING.md

# Theme
theme:
  name: material
  palette:
    primary: deep purple
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.suggest

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

plugins:
  - search

# Set docs directory
docs_dir: docs
site_dir: site
