# Language-specific Leyline sync workflow
# Place this file in your repository at .github/workflows/leyline-sync.yml

name: Leyline Sync (Language-Specific)
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  detect-language:
    name: Detect Project Languages
    runs-on: ubuntu-latest
    outputs:
      categories: ${{ steps.detect.outputs.categories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Languages and Set Categories
        id: detect
        run: |
          CATEGORIES=""

          # Check for TypeScript/JavaScript
          if find . -type f -name "*.ts" -o -name "*.tsx" -o -name "package.json" | grep -q .; then
            CATEGORIES="${CATEGORIES}typescript,"
          fi

          # Check for Go
          if find . -type f -name "*.go" -o -name "go.mod" | grep -q .; then
            CATEGORIES="${CATEGORIES}go,"
          fi

          # Check for Rust
          if find . -type f -name "*.rs" -o -name "Cargo.toml" | grep -q .; then
            CATEGORIES="${CATEGORIES}rust,"
          fi

          # Check for Frontend code
          if find . -type f -name "*.html" -o -name "*.css" -o -name "*.jsx" -o -name "*.tsx" | grep -q .; then
            CATEGORIES="${CATEGORIES}frontend,"
          fi

          # Remove trailing comma if it exists
          CATEGORIES=$(echo $CATEGORIES | sed 's/,$//')

          echo "categories=$CATEGORIES" >> $GITHUB_OUTPUT
          echo "Detected categories: $CATEGORIES"

  sync-docs:
    name: Sync Relevant Leyline Docs
    needs: detect-language
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Leyline
        uses: actions/checkout@v4
        with:
          repository: phrazzld/leyline
          ref: v0.1.0
          path: _leyline

      # Always sync all tenets (language-agnostic)
      - name: Sync Tenets
        run: |
          mkdir -p docs/tenets
          rsync -a --delete _leyline/docs/tenets/ docs/tenets/

      # Setup the bindings directory structure
      - name: Setup Bindings Directory Structure
        run: |
          mkdir -p docs/bindings/core
          mkdir -p docs/bindings/categories

      # Always sync core bindings
      - name: Sync Core Bindings
        run: |
          rsync -a --delete _leyline/docs/bindings/core/ docs/bindings/core/

      # Sync category-specific bindings based on detected categories
      - name: Sync Category-Specific Bindings
        if: ${{ needs.detect-language.outputs.categories != '' }}
        run: |
          # Split the categories string into an array
          IFS=',' read -ra CATEGORY_ARRAY <<< "${{ needs.detect-language.outputs.categories }}"

          # Sync each detected category
          for category in "${CATEGORY_ARRAY[@]}"; do
            if [ -d "_leyline/docs/bindings/categories/$category" ]; then
              echo "Syncing $category bindings"
              mkdir -p "docs/bindings/categories/$category"
              rsync -a --delete "_leyline/docs/bindings/categories/$category/" "docs/bindings/categories/$category/"
            else
              echo "Warning: Category directory not found for $category"
            fi
          done

      # Clean up any old binding structure if it exists
      - name: Clean Up Old Binding Structure
        run: |
          # Remove any old-style bindings in the flat structure
          find docs/bindings/ -maxdepth 1 -name "*.md" ! -name "00-index.md" -type f -delete || true

      # Regenerate the index file
      - name: Generate Bindings Index
        run: |
          cd _leyline
          ruby tools/reindex.rb
          cp docs/bindings/00-index.md ../docs/bindings/

      # Create PR with changes
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "docs: sync language-specific Leyline docs"
          body: |
            # Leyline Documentation Sync

            This PR automatically syncs Leyline tenets and bindings based on repository language detection.

            ## Synced Categories:
            - Core (always synced)
            ${{ needs.detect-language.outputs.categories != '' && format('- {0}', replace(needs.detect-language.outputs.categories, ',', '\n- ')) || '' }}

            Please review the synced documentation to ensure it's appropriate for your project.
          branch: leyline-sync
          commit-message: "docs: sync language-specific Leyline docs"
