# GitHub Actions workflow for syncing Leyline tenets and bindings
# Place this file in your repository at .github/workflows/sync-leyline.yml

name: Leyline Sync
on:
  # Run on pull requests to ensure docs are up to date
  pull_request:
  # Run on pushes to the default branch
  push:
    branches:
      - master  # Change this if your default branch has a different name

jobs:
  docs:
    name: Sync Leyline Content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Call the reusable workflow from the Leyline repository
      # This will sync tenets and bindings into your docs directory
      - name: Sync Leyline Content
        uses: phrazzld/leyline/.github/workflows/sync-leyline-content.yml@v1.0.0  # Update version as needed
        with:
          ref: v1.0.0  # Specify the version of Leyline to use
