name: ci
# This workflow validates all markdown files, ensuring they adhere to the YAML-only front-matter format
# Legacy horizontal rule metadata format is no longer supported
on: [push, pull_request]
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Node.js for markdown-link-check
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install Node.js link checker
    - name: Install markdown link checker
      run: npm install -g markdown-link-check

    - name: Essential CI Validation
      run: |
        echo "🚀 Running essential CI validation (fast mode)"
        echo "This validates only essential quality gates: YAML front-matter + Index consistency"
        export LEYLINE_STRUCTURED_LOGGING=true
        ruby tools/run_ci_checks.rb --essential
        if [ $? -ne 0 ]; then
          echo "::error::Essential validation failed!"
          echo "::error::Run 'ruby tools/run_ci_checks.rb --essential' locally to debug"
          exit 1
        fi
        echo "✅ Essential validation completed successfully"

    - name: External link validation
      run: |
        echo "🔗 Validating external links"
        find . -name "*.md" | grep -v "node_modules\|venv\|site" | xargs markdown-link-check -q -c ./.mlc-config
        if [ $? -ne 0 ]; then
          echo "::error::External link validation failed!"
          echo "::error::Some external links are broken or unreachable"
          exit 1
        fi
        echo "✅ External link validation completed successfully"
