name: ci
on: [push, pull_request]
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Node.js for markdown-link-check
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install Node.js link checker
    - name: Install markdown link checker
      run: npm install -g markdown-link-check

    - name: Link check
      run: |
        markdown-link-check -q -c ./.mlc-config '**/*.md'
    - name: Schema validate
      run: ruby tools/validate_front_matter.rb
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        pip install mkdocs mkdocs-material
        mkdocs build --strict
