name: Validate Content

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: false

    # Python validation disabled for documentation repository
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'

    # - name: Install Python linting tools
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 mypy

    - name: Validate YAML front-matter
      run: ruby tools/validate_front_matter.rb

    - name: Validate index consistency
      run: ruby tools/reindex.rb --strict

    # Python code validation disabled - documentation examples don't need strict production validation
    # - name: Validate Python code examples
    #   run: ruby tools/validate_python_examples.rb -v

    - name: Install gitleaks
      run: |
        # Install gitleaks for secret scanning
        curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz | tar -xzf - -C /tmp
        sudo mv /tmp/gitleaks /usr/local/bin/gitleaks
        gitleaks version

    - name: Scan Python bindings for secrets
      run: |
        echo "🔍 Scanning Python bindings for secrets..."
        if ! gitleaks dir docs/bindings/categories/python/ --no-color; then
          echo "❌ Secrets detected in Python binding examples!"
          echo "Please remove any hardcoded secrets, API keys, or credentials from code examples"
          echo "Use placeholder values like 'YOUR_API_KEY_HERE' or environment variable examples instead"
          exit 1
        fi
        echo "✅ No secrets detected in Python bindings"

    - name: Report validation results
      if: failure()
      run: |
        echo "❌ Content validation failed"
        echo "Please fix the errors above and commit again"
        exit 1
