name: Validate Content

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: false

    - name: CI Pipeline Health Check
      run: |
        echo "🏥 CI Pipeline Health Assessment"
        echo "================================"
        echo ""

        # Environment Information
        echo "📊 Environment Information:"
        echo "Runner OS: $(uname -a)"
        echo "Architecture: $(uname -m)"
        echo "Kernel: $(uname -r)"
        echo "Hostname: $(hostname)"
        echo "Date: $(date)"
        echo "User: $(whoami)"
        echo "Working Directory: $(pwd)"
        echo ""

        # Tool Version Inventory
        echo "🔧 Tool Version Inventory:"

        # Language Runtimes
        echo "Language Runtimes:"
        if command -v ruby >/dev/null 2>&1; then
          echo "  ✅ Ruby: $(ruby --version)"
        else
          echo "  ❌ Ruby: Not found"
        fi

        if command -v python3 >/dev/null 2>&1; then
          echo "  ⚠️  Python: $(python3 --version) (disabled for docs repo)"
        else
          echo "  ⚠️  Python: Not found (disabled for docs repo)"
        fi

        if command -v node >/dev/null 2>&1; then
          echo "  ℹ️  Node.js: $(node --version) (if needed)"
        else
          echo "  ℹ️  Node.js: Not found (optional)"
        fi
        echo ""

        # Required Ruby Tools
        echo "Ruby Tools:"
        if ruby -e "exit(0)" 2>/dev/null; then
          echo "  ✅ Ruby interpreter: Working"
        else
          echo "  ❌ Ruby interpreter: Failed basic test"
          exit 1
        fi

        # Validation Tools
        echo "Validation Tools:"
        if [ -f "tools/validate_front_matter.rb" ]; then
          echo "  ✅ validate_front_matter.rb: Present"
          if ruby tools/validate_front_matter.rb --help >/dev/null 2>&1; then
            echo "  ✅ validate_front_matter.rb: Functional"
          else
            echo "  ⚠️  validate_front_matter.rb: Help command failed (may still work)"
          fi
        else
          echo "  ❌ validate_front_matter.rb: Missing"
          exit 1
        fi

        if [ -f "tools/reindex.rb" ]; then
          echo "  ✅ reindex.rb: Present"
        else
          echo "  ❌ reindex.rb: Missing"
          exit 1
        fi
        echo ""

        # Git Information
        echo "📜 Git Information:"
        echo "Git version: $(git --version)"
        echo "Repository: $(git config --get remote.origin.url || echo 'No remote origin')"
        echo "Current branch: $(git branch --show-current)"
        echo "Latest commit: $(git log --oneline -1)"
        echo "Repository status: $(git status --porcelain | wc -l) modified files"
        echo ""

        # Disk Space Check
        echo "💾 Resource Status:"
        echo "Disk usage: $(df -h . | tail -1 | awk '{print $5 " used (" $4 " available)"}')"
        echo "Memory: $(free -h | grep '^Mem:' | awk '{print $3 "/" $2 " used"}')"
        echo ""

        # GitHub Actions Context
        echo "🎬 GitHub Actions Context:"
        echo "Event: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Job: ${{ github.job }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Run Number: ${{ github.run_number }}"
        echo "SHA: ${{ github.sha }}"
        echo ""

        echo "✅ Health check completed successfully"
        echo "🚀 Proceeding with validation pipeline..."

    # Python validation disabled for documentation repository
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'

    # - name: Install Python linting tools
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 mypy

    - name: Validate YAML front-matter
      run: ruby tools/validate_front_matter.rb

    - name: Validate index consistency
      run: ruby tools/reindex.rb --strict

    - name: Validate document length limits
      run: ruby tools/check_document_length.rb -v

    # Python code validation disabled - documentation examples don't need strict production validation
    # - name: Validate Python code examples
    #   run: ruby tools/validate_python_examples.rb -v


    - name: Report validation results
      if: failure()
      run: |
        echo "❌ Content validation failed"
        echo "Please fix the errors above and commit again"
        exit 1
