name: Validate Content

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: false

    # Python validation disabled for documentation repository
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'

    # - name: Install Python linting tools
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 mypy

    - name: Validate YAML front-matter
      run: ruby tools/validate_front_matter.rb

    - name: Validate index consistency
      run: ruby tools/reindex.rb --strict

    # Python code validation disabled - documentation examples don't need strict production validation
    # - name: Validate Python code examples
    #   run: ruby tools/validate_python_examples.rb -v

    - name: Scan Python bindings for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --source=docs/bindings/categories/python/ --verbose --no-color

    - name: Report gitleaks results
      if: failure()
      run: |
        echo "❌ Secrets detected in Python binding examples!"
        echo "Please remove any hardcoded secrets, API keys, or credentials from code examples"
        echo "Use placeholder values like 'YOUR_API_KEY_HERE' or environment variable examples instead"

    - name: Report validation results
      if: failure()
      run: |
        echo "❌ Content validation failed"
        echo "Please fix the errors above and commit again"
        exit 1
